import { Annotation } from "./annotation.model";
import { CritereCalculable } from "./critere-calculable.model";
import { Distinction } from "./distinction.model";
import { Expedition } from "./expedition.model";
import { GrilleTarifaire } from "./grille-tarifaire.model";
import { IndFraisAdd } from "./ind-frais-add.model";
import { IndPromo } from "./ind-promo.model";
import { InstCaractVar } from "./inst-caract-var.model";
import { InstCaract } from "./inst-caract.model";
import { InstClassif } from "./inst-classif.model";
import { InstCommentInt } from "./inst-comment-int.model";
import { Marque } from "./marque.model";
import { MonteeEnGamme } from "./montee-en-gamme.model";
import { TarifSaisonnier } from "./tarif-saisonnier.model";
import { TarifUnitVar } from "./tarif-unit-var.model";

export class ProduitSimple {
  _id?: string;
  refProduit?: string;
  refCB?: string;
  refQR?: string;
  typePS?: string;
  nouveau?: boolean;
  designation?: string;
  slogan?: string;
  madeIn?: string;
  descriptif?: string;
  resumeDescriptif?: string;
  imgPD?: string[];
  tag?: string;
  virtuel?: boolean;
  telechargeable?: boolean;
  urlExterne?: string;
  msgBtnComExterne?: string;
  affPublique?: boolean;
  affTarif?: number;
  venteSeule?: boolean;
  typeVente?: string;
  uniteProduit?: string;
  minCommande?: number;
  maxCommande?: number;
  typeTarif?: number;
  tarifUHT?: number;
  tVA?: number;
  pays?: string;
  tarVarParSaison?: boolean;
  tarVarParZoneGeo?: boolean;
  tarVarParDsbtr?: boolean;
  tarVarParVrte?: boolean;
  tarVarParQte?: boolean;
  notation?: number;
  affAvis?: boolean;
  etatPub?: string;
  msgAchat?: string;
  ordreAff?: number;
  gestStock?: boolean;
  indEtatStock?: boolean;
  expedition?: Expedition;
  annotations?: Annotation[];
  criteresCalculables?: CritereCalculable[];
  distinctions?: Distinction[];
  grilleTarifaires?: GrilleTarifaire[];
  instCaracterists?: InstCaract[];
  indicationPromo?: IndPromo[];
  indicationFraisAdd?: IndFraisAdd[];
  insCaractVar?: InstCaractVar;
  instClassifs?: InstClassif[];
  instCommentaireInterne?: InstCommentInt;
  marque?: Marque;
  monteeEnGamme?: MonteeEnGamme[];
  tarifSaisonnier?: Array<any>;
  tarifUV?: TarifUnitVar;
}
